py_version:
        #- 3.6 # [linux,win,osx-64]
    #- 3.7 # [linux,win,osx-64]
    #  - 3.8 # [linux,win,osx-64,osx-arm64]
    #- 3.9 # [linux,win,osx-64,osx-arm64]
  - 3.10 # [linux,win,osx-64,osx-arm64]

numpy:
        #- 1.19.2 # [linux,win,osx-64]
        #- 1.19.2 # [linux,win,osx-64]
        #- 1.21.5 # [linux,win,osx-64,osx-arm64]
        #- 1.21.5 # [linux,win,osx-64,osx-arm64]
  - 1.21.5 # [linux,win,osx-64,osx-arm64]

zip_keys:
  - py_version
  - numpy
